# -*- coding: utf-8 -*-
"""emotion_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTfQZky-6_UVv3GrjMax03jF9kDhhwEc
"""



from transformers import pipeline

# Load the pretrained emotion classifier from Hugging Face
classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      return_all_scores=True)

def detect_emotion(text):
    results = classifier(text)

    # Filter only 3 desired emotions
    desired_emotions = ['joy', 'anger', 'sadness']
    filtered = [e for e in results[0] if e['label'] in desired_emotions]

    if filtered:
        top = sorted(filtered, key=lambda x: x['score'], reverse=True)[0]
        label_map = {'joy': 'Happy', 'anger': 'Angry', 'sadness': 'Sad'}
        return label_map[top['label']], top['score']
    else:
        return "Unknown", 0

# Try input from user
text = input("Enter your sentence: ")
emotion, confidence = detect_emotion(text)

print(f"Predicted Emotion: {emotion} (Confidence: {confidence:.2f})")